ifneq ($(CONFIG_WIFI_MT7603E),)
obj-$(CONFIG_WIFI_MT7603E) += mt7603_wifi_ap/
endif
$(waring "=================================obj is obj-$(CONFIG_WIFI_MT7603E)========================================")


