ifneq ($(CONFIG_WIFI_MT7603E),)
obj-$(CONFIG_WIFI_MT7603E) += mt7603_wifi_ap/
endif
$(warning "=================================obj is obj-$(CONFIG_WIFI_MT7603E)========================================")


