$(warning "================================= src CONFIG_WIFI_MT7603E is $(CONFIG_WIFI_MT7603E) =====================================" )
ifneq ($(CONFIG_WIFI_MT7603E),)
obj-$(CONFIG_WIFI_MT7603E) += mt7603_wifi_ap/
endif


